version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: nodemon /home/app/app.js
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
      - /home/app/node_modules
